### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by rsmalc** [LaurensS/texlive-full#1]
How can I use this container from apache container? I have some php code which generate .tex file and I need to run this comant throught php exec('pdflatex doc.tex') command.

**Comment by LaurensS** [comment]
That indeed will not work since pdflatex will not be available in your Apache container.

The easiest solution for you will probably be to just install texlive in your image. 

If you do want to use this image in your scenario you will need to have docker in your image so you can execute `docker run … filename.tex` from within your Apache container. This will, however, require you to expose your docker socket to your apache container (see, for example, [this post]( https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)). For more information on this, I would suggest you take a look at the [overleaf repositories](https://github.com/overleaf/overleaf), they even have a [web api]( https://github.com/overleaf/clsi) for compiling LaTeX documents.

**Comment by rsmalc** [comment]
Thank you @LaurensS for your solution. 

The easiest solution it will be good for working. Only image get 3,5GB instead of 500MB when there is only apache and I will need to rebuilt id each time, when I change PHP version.

I will check you links.
